this commit adds the GET /api/articles/:article_id endpoint
harrycs1/news-api pull request #3
Opened 2023-11-20 16:18 UTC by harrycs1

2023-11-20 16:29 UTC, nc-verity-gregory requested changes
Not a bad effort. However your test for your article needs to fundamentally be re written. You are being specific in your request, expecting any returned data is not sufficient. Please make those changes and resubmit.

2023-11-20 16:29 UTC, nc-verity-gregory commented on __tests__/app.test.js
> +                    queries: expect.any(Object),
A tidy way to handle it, interesting.

2023-11-20 16:29 UTC, nc-verity-gregory commented on __tests__/app.test.js
> +            .get('/api/articles/2')
You are specifying id 2, you specifically want article 2. Does your test give you any confidence that you have article 2 and its corresponding information?

2023-11-20 16:29 UTC, nc-verity-gregory commented on controllers/topics.controllers.js
> +// this controller should be in it's own file?
Don't leave comments in that don't mean anything. Yes controllers that have different jobs should be in different files. Yes you'll need to update it every time. And Yes you should really test that the new endpoint in the json file is there.

2023-11-21 10:35 UTC, nc-jonathan-mcguire approved these changes
Looks all good to me 👍

2023-11-21 10:35 UTC, nc-jonathan-mcguire commented on __tests__/app.test.js
> +    })
nice sad path tests

2023-11-21 10:52 UTC, merged